name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Code lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Deploy to server
        run: |
          # Replace <SERVER_IP> with the actual IP address of your server
        #   ssh user@<SERVER_IP> "cd /path/to/project && git pull && npm install && npm run build"
